
### 회원가입
POST /api/auth/sign-up HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
"username": "kyuni9786",
"password": "12345abcd"
}

### 로그인
POST /api/auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "username": "kyuni9786",
  "password": "12345abcd"
}

### 목록 조회
GET /api/posts HTTP/1.1
Host: localhost:8080
Content-Type: application/json


### 글 작성
POST /api/posts HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJreXVuaTk3ODYiLCJleHAiOjE2ODg5NTc0OTksImlhdCI6MTY4ODk1Mzg5OX0.O1pPZSn82OWnWSA3_gGZMVxXKqGkZ-DFrt70N0dZ4iw

{
  "title": "title1",
  "content": "content1"
}

### 특정 게시물 조회
GET /api/posts/3 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJreXVuaTk3ODYiLCJleHAiOjE2ODg5NTc0OTksImlhdCI6MTY4ODk1Mzg5OX0.O1pPZSn82OWnWSA3_gGZMVxXKqGkZ-DFrt70N0dZ4iw



### 게시물 수정
PUT /api/posts/6 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJreXVuaTk3ODYiLCJleHAiOjE2ODg5NTc0OTksImlhdCI6MTY4ODk1Mzg5OX0.O1pPZSn82OWnWSA3_gGZMVxXKqGkZ-DFrt70N0dZ4iw


{
  "title": "Updated Post",
  "content": "This is an updated post content."
}

### 게시물 삭제
DELETE /api/posts/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJreXVuaTk3ODYiLCJleHAiOjE2ODg5NTc0OTksImlhdCI6MTY4ODk1Mzg5OX0.O1pPZSn82OWnWSA3_gGZMVxXKqGkZ-DFrt70N0dZ4iw


### 댓글 작성
POST http://localhost:8080/api/posts/3/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJreXVuaTk3ODYiLCJleHAiOjE2ODg5NTc0OTksImlhdCI6MTY4ODk1Mzg5OX0.O1pPZSn82OWnWSA3_gGZMVxXKqGkZ-DFrt70N0dZ4iw

{
  "content": "안녕하세요"
}

### 댓글 수정
PUT http://localhost:8080/api/posts/3/comments/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJreXVuaTk3ODYiLCJleHAiOjE2ODg5NTc0OTksImlhdCI6MTY4ODk1Mzg5OX0.O1pPZSn82OWnWSA3_gGZMVxXKqGkZ-DFrt70N0dZ4iw

{
  "content": "수정된 댓글 내용"
}

### 댓글 삭제
DELETE http://localhost:8080/api/posts/3/comments/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJreXVuaTk3ODYiLCJleHAiOjE2ODg5NTc0OTksImlhdCI6MTY4ODk1Mzg5OX0.O1pPZSn82OWnWSA3_gGZMVxXKqGkZ-DFrt70N0dZ4iw


